### ISSUE TITLE
Can it work in macOS?

### ISSUE THREAD

**Issue by inbalance** [Waujito/youtubeUnblock#18]
Hi!
Can it run in macOS? If there are some modifications I can make to run in macOS?

**Comment by Waujito** [comment]
Hi!
Sadly, here are no netfilter queue for macos https://github.com/oremanj/python-netfilterqueue/issues/2 
Maybe something like ByeDPI will work because it is a socs5 proxy, not a static packet analyzer/manager.
You can find some platform independent functions in kernel module branch of this module (there are not a complete, up to date set, but they may be helpful)
